### ISSUE TITLE
function already defined line 192

### ISSUE THREAD

**Issue by digiteinc** [digiteinfotech/rasa-dx#21]
#### Currently on:
+ **Commit**:  d8a2390be91e3c315ebbd4fce272ad65dcef22c0
+ **File**:    [bot_trainer/api/app/routers/bot.py](https://github.com/digiteinfotech/rasa-dx/blob/d8a2390be91e3c315ebbd4fce272ad65dcef22c0/bot_trainer/api/app/routers/bot.py)
+ **LineNum**: [210](https://github.com/digiteinfotech/rasa-dx/blob/d8a2390be91e3c315ebbd4fce272ad65dcef22c0/bot_trainer/api/app/routers/bot.py#L210)

**Comment by sfahad1414** [comment]
fixed 7742b42e11044406ea3a16154055b6ce528391d3
