### ISSUE TITLE
function already defined line 212

### ISSUE THREAD

**Issue by digiteinc** [digiteinfotech/rasa-dx#22]
#### Currently on:
+ **Commit**:  d8a2390be91e3c315ebbd4fce272ad65dcef22c0
+ **File**:    [bot_trainer/api/app/routers/bot.py](https://github.com/digiteinfotech/rasa-dx/blob/d8a2390be91e3c315ebbd4fce272ad65dcef22c0/bot_trainer/api/app/routers/bot.py)
+ **LineNum**: [251](https://github.com/digiteinfotech/rasa-dx/blob/d8a2390be91e3c315ebbd4fce272ad65dcef22c0/bot_trainer/api/app/routers/bot.py#L251)

**Comment by sfahad1414** [comment]
fixed d4f8b417de6a09752c573f9d9d2821dba919794d
